### ISSUE TITLE
求大神一个东西

### ISSUE THREAD

**Issue by xukongwen** [ZhipingYang/Spirality#3]
我是小白，刚学习swift，想做一个类似无限画板这样一个东西，里面都是grid，无论怎么pan和缩放，就是一个无限大grid画板。

各种实验都不行，不知道大神有没有思路，万分感谢！

**Comment by ZhipingYang** [comment]
这和swift没有关系的，CAD、EXcel之类的软件就是无限制的，这种场景用在矢量图上比较好。感觉scrollview就够了啊，放大缩小后重计算重绘画笔就好了吧

**Comment by xukongwen** [comment]
谢谢回复！我现在是用spritekit在做，还不能用苹果uikit里这些东西。这是一个小的游戏项目。[https://github.com/xukongwen/swift_learn](url)
大神可以看看我的笨方法！
谢谢！
